runtime: php81
basic_scaling:
  max_instances: 1
app_engine_apis: true
entrypoint: serve public/index.php
handlers:
  - url: /
    static_files: public/index.html
    upload: public/index.html
  - url: /(.*\.php)
    script: public/\1
  - url: /(.*)
    static_files: public/\1
    upload: public/.*
